### ISSUE TITLE
[Guide] Service name changes between examples

### ISSUE THREAD

**Issue by Deedasmi** [lukesteensen/tokio-example#1]
https://lukesteensen.com/2016/12/getting-started-with-tokio/

```
struct HelloWorldService;

impl Service for HelloWorldService
...
```

```
...
TcpServer::new(LineServerProto, addr)
        .serve(|| Ok(WorldService));
...
```

Code in the repo uses "WorldService'.

**Comment by lukesteensen** [comment]
Thanks!

**Comment by Deedasmi** [comment]
Are you going to fix the blog post as well? The bin code at the bottom uses WorldService as it was in the repo.

**Comment by lukesteensen** [comment]
Yep, it'll be updated in a few minutes.

**Comment by lukesteensen** [comment]
Updated.
